keras:
  image: jerrychiu/keras:latest
  tty: true
  stdin_open: true
  volumes:
    - ${volume_name}:${volume_mount_path}
  volume_driver: ${VOLUME_DRIVER}
  labels:
    io.rancher.container.pull_image: always
  ports:
    - ${jupyter_port}:8888
