digits:
  image: nvidia/digits:latest
  ports:
    - ${public_port}:34448/tcp
  privileged: true
  volumes:
    - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
    - ${volume_name}:${volume_mount_path}
  volume_driver: ${VOLUME_DRIVER}