.catalog:
  name: "DIGIT 4.0"
  version: digits4
  description: "Deep Learning"
  questions:
     - variable: "public_port"
       label: "Public Port"
       type: "int"
       required: true
       description: Public port to access the web site
       default: 34448