.catalog:
  name: "DIGIT 4.0"
  version: digits4
  description: "Deep Learning"
  questions:
     - variable: "public_port"
       label: "Public Port"
       type: "int"
       required: true
       description: Public port to access the web site
       default: 34448
     - variable: "VOLUME_DRIVER"
       label: "Volume driver"
       type: "string"
       required: true
       description: Driver that is providing volume
       default: "convoy-gluster"
     - variable: "volume_name"
       label: "Volume Name"
       type: "string"
       required: true
       description: The volume name to store your datasets
       default: "digits_volume"
     - variable: "volume_mount_path"
       label: "Volume Mount Path"
       type: "string"
       required: true
       description: The mount path of your data volume
       default: "/root"
