amb-db:
  environment:
    POSTGRES_PASSWORD: bigdata
    POSTGRES_USER: ambari
  labels:
    io.rancher.container.pull_image: always
  image: 10.32.76.253:5000/cloud/ambari-db
  volumes:
  - /mnt/volume/data/ambari-server/pgsql/data:/var/lib/postgresql/data
consul:
  domainname: service.consul
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.requested_ip: 10.42.2.24
  command:
  - -server
  - -bootstrap
  hostname: consul
  image: sequenceiq/consul:v0.5.0-v6
amb-agent:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  command:
  - systemd.setenv=CLOUD_PLATFORM=RANCHER
  image: 10.32.76.253:5000/cloud/ambari-agent
  privileged: true
  volumes:
  - /mnt/volume/hadoop:/hadoop
  links:
  - amb-server:amb-server
  - amb-db:amb-db
  - consul:consul
  - manager:manager
  dns_search:
  - service.consul
  - node.dc1.consul
  dns:
  - 10.42.2.24
amb-server:
  ports:
  - 8080:8080/tcp
  labels:
    io.rancher.container.pull_image: always
  command:
  - systemd.setenv=CLOUD_PLATFORM=RANCHER
  - systemd.setenv=POSTGRES_DB=amb-db
  image: 10.32.76.253:5000/cloud/ambari-server
  privileged: true
  links:
  - amb-db:amb-db
  - consul:consul
  dns_search:
  - service.consul
  - node.dc1.consul
  dns:
  - 10.42.2.24
provision:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  links:
  - amb-server:ambariserver
  environment:
    EXPECTED_HOST_COUNT: ${node_count}
    HDP_BASE_URL: http://192.168.141.122/HDP/centos7/2.x/updates/2.4.0.0
    HDP_REPO_URI: api/v1/stacks/HDP/versions/2.4/operating_systems/redhat7/repositories/HDP-2.4
    HDP_UTILS_BASE_URL: http://192.168.141.122/HDP-UTILS-1.1.0.20/repos/centos7
    HDP_UTILS_REPO_URI: api/v1/stacks/HDP/versions/2.4/operating_systems/redhat7/repositories/HDP-UTILS-1.1.0.20
    BLUEPRINT: multi-node-persp
    #BLUEPRINT: ${blueprint}
  entrypoint:
  - /bin/bash
  - -c
  - /tmp/install-cluster.sh
  image: 10.32.76.253:5000/cloud/ambari-server
  tty: true
  stdin_open: true
  dns_search:
  - service.consul
  - node.dc1.consul
  dns:
  - 10.42.2.24
kerberos:
  labels:
    io.rancher.container.pull_image: always
  image: 10.32.76.253:5000/sean/persp-kerberos
  links:
  - amb-db:amb-db
  - consul:consul
  tty: true
  stdin_open: true
  dns_search:
  - service.consul
  - node.dc1.consul
  dns:
  - 10.42.2.24
manager:
  ports:
  - 80:80/tcp
  labels:
    io.rancher.container.pull_image: always
  image: 10.32.76.253:5000/sean/persp-manager
  links:
  - amb-db:amb-db
  - consul:consul
  tty: true
  stdin_open: true
  dns_search:
  - service.consul
  - node.dc1.consul
  dns:
  - 10.42.2.24
hue:
  ports:
  - 8888:8888/tcp
  labels:
    io.rancher.container.pull_image: always
  image: 10.32.76.253:5000/sean/persp-hue
  privileged: true
  links:
  - amb-db:amb-db
  - consul:consul
  - manager:manager
  tty: true
  stdin_open: true
  dns_search:
  - service.consul
  - node.dc1.consul
  dns:
  - 10.42.2.24
proxy:
  ports:
  - 8443:8443/tcp
  - 10000:10000/tcp
  - 88:88/tcp
  labels:
    io.rancher.container.pull_image: always
  image: 10.32.76.253:5000/sean/persp-proxy
  links:
  - consul:consul
  - manager:manager
  tty: true
  stdin_open: true
  dns_search:
  - service.consul
  - node.dc1.consul
  dns:
  - 10.42.2.24
