dd-app:
  environment:
    FXN_MODEL_PATH : ${FXN_MODEL_PATH}
  ports:
  - ${FXN_PUBLIC_PORT}:8080/tcp
  - ${FXN_PROXY_PORT}:1337/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: true
  image: markyeh/dd-app:v0.0.5-2016.1218
  volumes:
  - /var/lib/nvidia-docker/volumes/nvidia_driver/367.48:/usr/local/nvidia:ro
  privileged: true

inference-client:
  image: jerrychiu/inference_client:v0.1
  ports:
  - ${WEB_INFERENCE_PORT}:5000/tcp
  labels:
    io.rancher.container.pull_image: always
  links:
    - dd-app:dd_serving
  privileged: true
  environment:
      SERVING_PORT: 8080

dd-admin:
  image: jerrychiu/dl_admin:v0.1
  ports:
  - ${WEB_ADMIN_PORT}:80/tcp
  labels:
    io.rancher.container.pull_image: always
  links:
    - dd-app:dd_serving
  privileged: true
  environment:
      SERVING_PORT: 1337
