digits4:
  image: nvidia/digits:4.0-ubuntu14.04
  ports:
    - ${public_port}:34448/tcp
  privileged: true
  labels:
    io.rancher.container.pull_image: always
  volumes:
    - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
    - ${volume_name}:${volume_mount_path}
  volume_driver: ${VOLUME_DRIVER}
