mxnet:
  image: jerrychiu/cuda-mxnet:latest
  tty: true
  stdin_open: true
  privileged: true
  volumes:
    - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
    - ${volume_name}:${volume_mount_path}
  volume_driver: ${VOLUME_DRIVER}
  ports:
    - ${jupyter_port}:8888
  labels:
    io.rancher.container.pull_image: always
