theano:
  image: kaixhin/cuda-theano:latest
  volumes:
    - /var/lib/nvidia-docker/volumes/nvidia_driver/361.45.18:/usr/local/nvidia:ro
    - ${volume_name}:${volume_mount_path}
  volume_driver: ${VOLUME_DRIVER}
