fxndl:
  image: fxndl:0.1
  links:
    - db:mysql
    - jar:caffeonspark
  privileged: true
  ports:
    - ${digits_port}:5000
  environment:
    SPARK_HOST: ${spark_host}
    SPARK_SSH_PORT: ${ssh_port}
    SPARK_USER: ${spark_account}
    SPARK_PASSWORD: ${spark_password}

jar:
  image: markyeh/caffe-spark
  privileged: true
  ports:
    - ${jar_port}:80

db:
  image: mariadb
  privileged: true
  environment:
    MYSQL_ROOT_PASSWORD: fxndl
    MYSQL_USER: digits
    MYSQL_PASSWORD: digits
