fxndl:
  image: fxndl:0.1
  links:
    - db:mysql
  ports:
    - ${public_port}:5000

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: fxndl
    MYSQL_USER: digits
    MYSQL_PASSWORD: digits
