.catalog:
  name: "FOXCONN DEEP LEARNING"
  version: "v0.1"
  description: "FOXCONN DEEP LEARNING"
  uuid: fxndl-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: digits_port
      description: "public port to access the fxndl site"
      label: "Digits Public Port"
      required: true
      default: "5000"
      type: "int"
    - variable: "spark_host"
      type: string
      required: true
      label: "Spark Cluster Host"
      description: "Address of Host for Spark Cluster"
    - variable: "spark_account"
      type: string
      required: true
      label: "Spark Account"
      description: "User account of Host for Spark Cluster"
    - variable: ssh_port
      description: "public SSH port of Host for Spark Cluster"
      label: "Public SSH Port"
      required: true
      default: "22"
      type: "int"
    - variable: "spark_password"
      type: password
      required: true
      label: "Spark Password"
      description: "Address of Host for Spark Cluster"
    - variable: jar_port
      description: "public port to access the Caffe on Spark site"
      label: "Caffe on Spark Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: "volume_driver"
      label: "Volume Driver"
      type: string
      required: true
      description: "volume driver"
    - variable: "volume_name"
      type: string
      required: true
      label: "The volume name on host"
      description: "The volume name on host"

fxndl:
  scale: 3
  health_check:
      initializing_timeout: 120000
      port: 5000
      interval: 5000
      unhealthy_threshold: 2
      strategy: recreate
      response_timeout: 5000
      healthy_threshold: 1
jar:
  health_check:
      port: 80
      interval: 5000
      unhealthy_threshold: 2
      strategy: recreate
      response_timeout: 5000
      healthy_threshold: 1
db:
  health_check:
      port: 3306
      interval: 5000
      unhealthy_threshold: 2
      strategy: recreate
      response_timeout: 5000
      healthy_threshold: 1
fxndl-lb:
  scale: 1
  load_balancer_config: {}
  health_check:
    port: 42
    interval: 5000
    unhealthy_threshold: 2
    strategy: recreate
    healthy_threshold: 1
    response_timeout: 5000
