amb-agent:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  command:
  - systemd.setenv=USE_CONSUL_DNS=false
  - systemd.setenv=AMBARI_SERVER_ADDR=ambariserver
  - systemd.setenv=CLOUD_PLATFORM=RANCHER
  image: cloudchchen/ambari-agent:latest
  links:
  - amb-server:ambariserver
  privileged: true
amb-server:
  ports:
  - 8080:8080/tcp
  labels:
    io.rancher.container.pull_image: always
  command:
  - systemd.setenv=USE_CONSUL_DNS=false
  - systemd.setenv=CLOUD_PLATFORM=RANCHER
  image: cloudchchen/ambari-server:latest
  privileged: true
provision:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  entrypoint:
  - /bin/bash
  image: hortonworks/ambari-server
  links:
  - amb-server:ambariserver
  stdin_open: true
  environment:
    EXPECTED_HOST_COUNT: ${node_count}
    BLUEPRINT: ${blueprint}
