.catalog:
  name: "Tensorflow latest (CPU only)"
  version: Latest (CPU only)
  description: "Deep Learning"
  questions:
     - variable: "PUBLIC_PORT"
       label: "Public Port"
       type: "int"
       required: true
       description: Public port to access the web site
       default: 32458
     - variable: "VOLUME_DRIVER"
       label: "Volume driver"
       type: "string"
       required: true
       description: Driver that is providing volume
       default: "convoy-gluster"
     - variable: "VOLUME_NAME"
       label: "Volume Name"
       type: "string"
       required: true
       description: The volume name to store your datasets
       default: "tensorflow_volume"
     - variable: "VOLUME_MOUNT_PATH"
       label: "Volume Mount Path"
       type: "string"
       required: true
       description: The mount path of your data volume
       default: "/datasets"