.catalog:
  name: "Distributed Tensorflow with CUDA"
  version: Distributed (GPU)
  description: "Deep Learning"
  questions:
    - variable: "WORKER_NUM"
      label: "worker number"
      type: "int"
      default: 2
      required: true
      description: worker number setting
    - variable: "PUBLIC_PORT"
       label: "Public Port"
      type: "int"
      default: 8888
      required: false
      description: jupyter-notebooks public port
     - variable: "VOLUME_DRIVER"
       label: "Volume driver"
       type: "string"
       required: true
       description: Driver that is providing volume
       default: "convoy-nfs"
     - variable: "VOLUME_NAME"
       label: "Volume Name"
       type: "string"
       required: true
       description: The volume name to store your datasets
       default: "tensorflow_volume"
     - variable: "VOLUME_MOUNT_PATH"
       label: "Volume Mount Path"
       type: "string"
       required: true
       description: The mount path of your data volume
       default: "/datasets"
tf-jupyter:
  scale: 1
tf-worker:
  scale: ${WORKER_NUM}
tf-ps:
  scale: 1
