.catalog:
  name: "DIGITS latest (CPU only)"
  version: No-Volume
  description: "Deep Learning"
  questions:
     - variable: "public_port"
       label: "Public Port"
       type: "int"
       required: true
       description: Public port to access the web site
       default: 34458
