digitscpu4:
  image: casperc2100/digits:4.0-cpu
  ports:
    - ${public_port}:5000/tcp
  privileged: true
  labels:
    io.rancher.container.pull_image: always
  volumes:
    - ${volume_name}:${volume_mount_path}
  volume_driver: ${VOLUME_DRIVER}