amb-db:
  environment:
    POSTGRES_PASSWORD: bigdata
    POSTGRES_USER: ambari
  labels:
    io.rancher.container.pull_image: always
  command:
  - postgres
  hostname: amb-db
  image: postgres
  volumes:
  - /data/ambari-server/pgsql/data:/var/lib/postgresql/data
amb-agent:
#  ports:
#  - 8088:8088/tcp
#  - 18080:18080/tcp
#  - 4040:4040/tcp
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  command:
  - systemd.setenv=CLOUD_PLATFORM=RANCHER
#  - systemd.setenv=USE_CONSUL_DNS=false
#  - systemd.setenv=AMBARI_SERVER_ADDR=amb-server
#  - systemd.setenv=CONSUL_DNS_IP=${consul_dns_ip}
  image: cloudchchen/ambari-agent:latest
  privileged: true
  volumes:
  - /hadoop:/hadoop
  dns_search:
  - service.consul
  - node.dc1.consul
  dns:
  - ${consul_dns_ip}
amb-server:
  ports:
  - 8080:8080/tcp
  labels:
    io.rancher.container.pull_image: always
  command:
  - systemd.setenv=CLOUD_PLATFORM=RANCHER
  - systemd.setenv=POSTGRES_DB=amb-db
#  - systemd.setenv=USE_CONSUL_DNS=false
#  - systemd.setenv=CONSUL_DNS_IP=${consul_dns_ip}
  image: cloudchchen/ambari-server:latest
  privileged: true
  links:
  - amb-db:amb-db
  dns_search:
  - service.consul
  - node.dc1.consul
  dns:
  - ${consul_dns_ip}
#consul-dns:
#  labels:
#    io.rancher.container.pull_image: always
#  command:
#  - -server
#  - -bootstrap
#  image: sequenceiq/consul:v0.5.0-v6
provision:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  entrypoint:
  - /bin/bash
  image: hortonworks/ambari-server
  links:
  - amb-server:ambariserver
  stdin_open: true
  environment:
    EXPECTED_HOST_COUNT: ${node_count}
    BLUEPRINT: ${blueprint}
