mxnet:
  image: jerrychiu/mxnet:latest
  tty: true
  stdin_open: true
  volumes:
    - ${volume_name}:${volume_mount_path}
  volume_driver: ${VOLUME_DRIVER}
  ports:
    - ${shellinabox_port}:4200
  labels:
    io.rancher.container.pull_image: always
  environment:
    SIAB_USER: ${shellinabox_user}
    SIAB_PASSWORD: ${shellinabox_password}
    SIAB_SUDO: true
