fxnfr:
  image: mattwang201301/fxnfr:0.1
  privileged: true
  environment:
    STREAM_ADDR: ${stream_addr}
  ports:
    - ${web_port}:8000
    - ${slot_port}:11843
  labels:
    io.rancher.container.pull_image: always
