tensorflow:
  ports:
  - ${PUBLIC_PORT}:8888/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  entrypoint:
  - /bin/sh
  - -c
  - jupyter notebook --port=8888 --ip=0.0.0.0
  image: davidchiu/tensorflow_r011:gpu-v0.3
  privileged: true
  volumes:
  - /var/lib/nvidia-docker/volumes/nvidia_driver/367.48:/usr/local/nvidia:ro
  stdin_open: true